config/routes.rb
Rails.application.routes.draw do
  
  root 'authors#home'
  resources :authors do
    resources :blogs
  end
  get '/blogs',to:'blogs#index'
  get "/list",to: "blogs#list"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :blogs, dependent: :destroy
  validates :firstname, presence: true
  validates :age, presence: true
  validates :email, :uniqueness => {:allow_blank => true}
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :author

  validates :title, presence: true
  validates :content, presence: true, length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/author/confirmations_controller.rb
# frozen_string_literal: true

class Author::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/author/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Author::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/author/passwords_controller.rb
# frozen_string_literal: true

class Author::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/author/registrations_controller.rb
# frozen_string_literal: true

class Author::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  def sign_up_params
    params.require(:user).permit(:firstname, :firstname, :age, :email, :password)
  end

  def account_update_params
    params.require(:user).permit(:name, :line1, :line2, :town, :county, :postcode)
  end
end

app/controllers/author/sessions_controller.rb
# frozen_string_literal: true

class Author::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/author/unlocks_controller.rb
# frozen_string_literal: true

class Author::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def home
    
  end
  
  def index
    @authors=Author.all
  end

  def new 
    @author=Author.new
  end

  def show
    @author=Author.find(params[:id])
  end 

  def create
    @author=Author.new(author_params)
    if @author.save
      redirect_to @author
    else 
      render :new
    end
  end

  def edit
    @author=Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to @author
    else
      render :edit
    end
  end

  def destroy
    @author=Author.find(params[:id])
    @author.destroy

    redirect_to root_path
  end


  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:firstname, :lastname, :age, :email, :password, :password_confirmation) }
    end
 
    def author_params
      params.require(:author).permit(:firstname, :lastname,:age)
    end

end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs=Blog.all
  end

  def list
    @blogs=Blog.all
  end

  def show
    @blog = Blog.find(params[:id])
  end

  def new 
    @blog=Blog.new
  end

  def create
    @author=Author.find(params[:author_id])
    @blog=@author.blogs.create(blog_params)

    redirect_to author_path(@author)
  end

  def destroy
    @author = Author.find(params[:author_id])
    @blog = @author.blogs.find(params[:id])
    @blog.destroy
    
    redirect_to author_path(@author)
  end

  def edit
    @blog=Blog.find(params[:id])
  end

  def update
    @blog = Blog.find(params[:id])

    if @blog.update(blog_params)
      redirect_to @blog
    else
      render :edit
    end
  end

  def destroy
    @blog=Blog.find(params[:id])
    @blog.destroy

    redirect_to root_path
  end

  private
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/authors/_form.html.erb
<div class="form-group">
  <%= form_with model: @author do |form| %>
  <div>
    <%= form.label :firstname %><br />
    <%= form.text_field :firstname,class:"form-control" %>
    <% @author.errors.full_messages_for(:firstname).each do |message| %>
    <div><%= message %></div>
    <%end%>
  </div>

  <div>
    <%= form.label :lastname %><br />
    <%= form.text_field :lastname,class:"form-control" %> <%
    @author.errors.full_messages_for(:lastname).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :age %><br />
    <%= form.text_field :age,class:"form-control" %> <%
    @author.errors.full_messages_for(:age).each do |message| %>
    <div><%= message %></div>
    <% end %>
  </div>

  <div><%= form.submit %></div>
  <% end %>
</div>

app/views/authors/edit.html.erb
<div class="container">
  <h1>Edit Blog</h1>
  <%= render "form", author:@author %>
</div>  

app/views/authors/home.html.erb
<div class="home_hero">
  <div class="container text-center  text-white">
    <br><br>
    <h1>Publish your passions, your way</h1>
    <h4>Create a unique and beautiful blog. It’s easy and free.</h4>
    <button class="btn btn-warning mt-5 text-white">CREATE YOUR BLOG</button>
  </div>
  <div class="container mt-5 text-center col d-flex justify-content-center">
    <div class="my_blog">
      <div id="main_card" class="card rounded" >
        <%= image_tag 'food_one.jpg', alt: 'icon', :class=>"card-image-top" %>
        <div class="card-body">
          <h5 class="card-title">My Blog</h5>
        </div>
      </div>
    </div>
  </div>
  <div class="hero_two ">
    <div class= "container text-white py-5"> <br><br>
      <div class="row intro_two">
        <div class="col-7"><h2>Choose the perfect design</h2>
          <h4>Create a beautiful blog that fits your style. Choose from a selection of easy-to-use templates – all with flexible layouts and hundreds of background images – or design something new.</h4>
        </div>
        <div class="col-4">
          <%= image_tag 'blog_two.jpg', alt: 'icon', :class=>"img-responsive" %>
        </div>
      </div>
    </div>
  </div>
  <div class="hero_three ">
    <div class= "container text-white py-5"> <br><br>
      <div class="row intro_two">
        <div class="col-7"><h2>Get a free domain</h2>
          <h4>Give your blog the perfect home. Get a free blogspot.com domain or buy a custom domain with just a few clicks.</h4>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/authors/index.html.erb
<div class="container">
  <h1>Authors</h1>

  <table class="table">
    <thead>
      <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Age</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @authors.each do |author| %>
        <tr>
          <td><a href="<%= author_path(author) %>"> <%= author.firstname %> </a></td>
          <td><%= author.lastname %></td>
          <td><%= author.age %></td>
          <td><%= link_to "Edit", edit_author_path(author) %></td>
          <td><%= link_to "Destroy", author_path(author), method: :delete, data: {
            confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to "New Author",new_author_path %>
</div>

app/views/authors/new.html.erb
<div class="container">
  <h1>New Author</h1>
  <%= render "form", author:@author %>
</div>

app/views/authors/show.html.erb
<div class="container">
  <br> <br>
  <div class="row">
    <div class="col">
      <h1><%= @author.firstname %></h1>

      <h3><%= @author.firstname %> <%= @author.lastname %>, <%= @author.age %></h3>
    </div>
    <div class="col">
      <br><br>
      <%= link_to "Edit", edit_author_path(@author) %> &nbsp;
        <%= link_to "Destroy", author_path(@author), method: :delete, data: {
        confirm: "Are you sure?" } %>
    </div>
  </div>

  <br>
  <h1>Blogs</h1>
  <% if @author.blogs.length==0 %>
    No Blogs!
    <% else %>
    <%= render @author.blogs %>
  <% end %>
    <br><br>
  <h2>Add a Blog:</h2>
  <%= form_with model: [ @author, @author.blogs.build ] do |form| %>
  <p>
    <%= form.label :title %><br />
    <%= form.text_field :title,class:"form-control" %>
  </p>
  <p>
    <%= form.label :content %><br />
    <%= form.text_field :content,class:"form-control" %>
  </p>
  <p><%= form.submit %></p>
  <% end %>
</div>

app/views/blogs/_blog.html.erb
<p>
  <strong>Title:</strong>
  <%= blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= blog.content %>
</p>

<p>
  <%= link_to 'Destroy Blog', [blog.author, blog],
              method: :delete,
              data: { confirm: "Are you sure?" } %>
</p>

app/views/blogs/index.html.erb
<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Content</th>
      </tr>
    </thead>
    <tbody>
      <% @blogs.each do |blog| %>
      <tr>
        <th scope="row"><%= blog.id %></th>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
      </tr>
      <% end %>
      </tbody>
  </table>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light navy sticky-top">
  <a class="navbar-brand" href="/">Daily Blogs</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/authors">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Quote Of The Day</a>
      </li>
    </ul>
    <% if @user%>
    <span class="navbar-text">
      Welcome, <%= user.username %>
    </span>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DailyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300;400&display=swap" rel="stylesheet">    <style>
      body{
        font-family: 'Titillium Web', sans-serif;
      } 
    </style>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>  </body>
</html>